---
- name: Playbook for initial setup
  hosts: raspberry_pi
  user: dmndpl
  roles:
    - common
    - rpi_exporter
    - node_exporter

- hosts: monitoring_server
  user: dmndpl
  roles:
    - monitoring_server
