---
- name: Playbook for initial setup
  hosts: raspberry_pi
  user: pi  
  roles:
    - common
    - rpi_exporter
    - node_exporter
    - k3s_prereq
    - k3s_download

- hosts: monitoring_server
  user: pi
  roles:
    - monitoring_server

- hosts: k3s_worker
  user: pi
  become: yes
  gather_facts: yes
  roles:
    - k3s_worker

- hosts: k3s_coordinator
  user: pi
  become: yes
  gather_facts: yes
  roles:
    - k3s_coordinator
