---
serviceName: "prometheus"
userId: "prometheus"
groupId: "prometheus"
exec_command: "/usr/local/bin/prometheus --log.level=debug --config.file=/etc/prometheus/prometheus.conf --storage.tsdb.path=/data/prometheus --storage.tsdb.retention=1d"
prometheusVersion: "2.20.1"
grafanaVersion: "7.0.0"
